# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-11 14:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('normal_price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('pintuan_price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('add_time', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='FoodCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='FoodImages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
                ('food', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.Food')),
            ],
        ),
        migrations.CreateModel(
            name='PinTuan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pintuan_from', models.DateTimeField()),
                ('pintuan_end', models.DateTimeField()),
                ('food_from', models.DateTimeField()),
                ('food_end', models.DateTimeField()),
                ('per_limit', models.IntegerField(default=1)),
                ('if_cancel', models.BooleanField(default=False)),
                ('total_count', models.IntegerField()),
                ('left_count', models.IntegerField()),
                ('create_time', models.DateTimeField(auto_now=True)),
                ('delete_time', models.DateTimeField(blank=True, null=True)),
                ('expires', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='ShopInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('vote', models.DecimalField(blank=True, decimal_places=1, default=0, max_digits=3, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=12, null=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=12, null=True)),
                ('shopID', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('create_time', models.DateTimeField(auto_now=True)),
                ('category', models.ManyToManyField(to='shop.FoodCategory')),
            ],
        ),
        migrations.CreateModel(
            name='TuanFeature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='TuanMode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='pintuan',
            name='feature',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.TuanFeature'),
        ),
        migrations.AddField(
            model_name='pintuan',
            name='food',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.Food'),
        ),
        migrations.AddField(
            model_name='pintuan',
            name='food_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.FoodCategory'),
        ),
        migrations.AddField(
            model_name='pintuan',
            name='mode',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.TuanMode'),
        ),
        migrations.AddField(
            model_name='food',
            name='shop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.ShopInfo'),
        ),
    ]
